# Generated by Django 4.1.1 on 2022-09-14 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningFacilitators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lf_name', models.CharField(max_length=15, null=True)),
                ('students_scores', models.IntegerField(max_length=20, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=15, null=True)),
                ('student_id', models.SmallIntegerField(max_length=10, null=True)),
                ('student_course', models.CharField(max_length=20, null=True)),
                ('student_scores', models.CharField(choices=[('-2', 'Very Unsatisfied'), ('-1', 'Unsatisfied'), ('0', 'Nuetral'), ('1', 'Satisfied'), ('2', 'Very Satisfied')], max_length=15, null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=6, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
