# Generated by Django 4.1.1 on 2022-09-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningfacilitators',
            name='students_scores',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_scores',
            field=models.CharField(choices=[('Very Unsatisfied', '-2'), ('Unsatisfied', '-1'), ('Nuetral', '0'), ('Satisfied', '1'), ('Very Satisfied', '2')], max_length=30, null=True),
        ),
    ]
