# Generated by Django 4.0.6 on 2022-09-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_learningfacilitators_students_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningfacilitators',
            name='student_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
